vercel env add NEXT_PUBLIC_SUPABASE_URL production
vercel env add NEXT_PUBLIC_SUPABASE_ANON_KEY production
vercel env add SUPABASE_SERVICE_ROLE_KEY production
vercel env add SUPABASE_ACCESS_TOKEN production
vercel env add ANTHROPIC_API_KEY production
vercel env add OPENAI_API_KEY production
vercel env add GROQ_API_KEY production
vercel env add LLM_PROVIDER production
vercel env add ANTHROPIC_MODEL production
vercel env add OPENAI_MODEL production
vercel env add GROQ_MODEL production
vercel env add OPENAI_EMBEDDING_MODEL production
vercel env add UPSTASH_REDIS_REST_URL production
vercel env add UPSTASH_REDIS_REST_TOKEN production
vercel env add NODE_ENV production
vercel env add BACKEND_URL production
vercel env add NEXTAUTH_SECRET production
vercel env add NEXTAUTH_URL production